apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: elasticsearch-master-config
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}
    #network.host: 0.0.0.0
    node.roles : [master]
    xpack.license.self_generated.type: basic
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
    xpack.security.authc.api_key.enabled: true    
    xpack.security.enrollment.enabled: true
    xpack.security.transport.ssl.enabled: true   
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    xpack.security.http.ssl.enabled: true
    xpack.security.http.ssl.verification_mode: certificate
    xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
    xpack.security.http.ssl.client_authentication: optional
    #xpack.security.authc.realms.pki1.type: pki
    #xpack.security.authc.realms.pki.pki1.order: 1
---
kind: Service
apiVersion: v1
metadata:
  namespace: logging
  name: es-master
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9300
      name: inter-node
    - port: 9200
      name: rest
  selector:
    app: elasticsearch

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: logging
  name: es-master
  labels:
    app: elasticsearch
    role: master
spec:
  serviceName: es-master
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch-master
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: "8Gi"
            requests:
              cpu: 500m
              memory: "4Gi"
          ports:
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - name: elasticsearch-master-persistent-storage
              mountPath: /data/db
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              readOnly: true
              subPath: elasticsearch.yml
            - name: certs
              mountPath: /usr/share/elasticsearch/config/certs
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              value: $(HOSTNAME).es-master.logging.svc.cluster.local
            - name: network.host
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_NAME
              value: elasticsearch-cluster
            - name: MASTER_NODES
              value: "es-master-0.es-master.logging.svc.cluster.local"
            - name: NODE_LIST
              value: es-master-0.es-master.logging.svc.cluster.local,es-master-1.es-master.logging.svc.cluster.local,es-master-2.es-master.logging.svc.cluster.local #csv values of every master
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
      volumes:
        - name: config
          configMap:
            name: elasticsearch-master-config
        - name: certs
          secret:
            secretName: elasticsearch-certs
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master-persistent-storage
        labels:
          app: elasticsearch
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: elk-azurefile-sc
        resources:
          requests:
            storage: 5Gi
