apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-test-config
  labels:
    app: elasticsearch
    role: client
data:
  elasticsearch.yml: |-
    network.host: 0.0.0.0
    xpack.license.self_generated.type: basic
    xpack.security.enabled: false
    discovery.type: single-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-test
  labels:
    app: elasticsearch
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      role: client
  template:
    metadata:
      labels:
        app: elasticsearch
        role: client
    spec:
      containers:
        - name: elasticsearch-test
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
          imagePullPolicy: "IfNotPresent"
          env:
            - name: CLUSTER_NAME
              value: elasticsearch-test-cs
            - name: NODE_NAME
              value: elasticsearch-test
            - name: NODE_LIST
              value: elasticsearch-test
            - name: "ES_JAVA_OPTS"
              value: "-Xms2g -Xmx2g"
          ports:
            - containerPort: 9200
              name: client
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              readOnly: true
              subPath: elasticsearch.yml
            - name: storage
              mountPath: /data
          resources:
            limits:
              cpu: 500m
              memory: "4Gi"
            requests:
              cpu: 300m
              memory: "2Gi"
      volumes:
        - name: config
          configMap:
            name: elasticsearch-test-config
        - name: "storage"
          emptyDir:
            medium: ""
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
            runAsUser: 0
        - name: increase-fd-ulimit
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "ulimit -n 65535"]
          securityContext:
            privileged: true
            runAsUser: 0

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-test
  labels:
    app: elasticsearch
    role: client
spec:
  ports:
    - port: 9200
      name: client
    - port: 9300
      name: transport
  selector:
    app: elasticsearch-test
    role: client
